### PR TITLE
Add supplements for the NL Braillo table

### PR DESCRIPTION
**Pull request by dkager**
This adds a few supplements to make comparing Dedicon's current system with the DP2 project easier, as discussed with @bertfrees. Sorry about the multiple PRs for this single table. :)

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks Davy. I'll first test this and will let @joeha480 know when ready.

**Comment by bertfrees** [comment]
Can be merged I think.

**Comment by joeha480** [comment]
I don't know why it says there are unmerged commits. I did the same thing as last time (i.e. squash the fixup).

**Comment by bertfrees** [comment]
Don't know what Github usually says in these cases, looks like it was merged just fine.

**Comment by dkager** [comment]
I think it tries to auto-close PRs as much as possible. Guess it got too clever for its own good. J

**Pull request closed without merging**
